kumuluzee:
  name: userservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
    base-url: http://localhost:8080
  datasources:
  - jndi-name: jdbc/userservice
    connection-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skiprope
    max-pool-size: 2

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/userservice
      disk-space-health-check:
        threshold: 100000000

  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /api/*
        status-codes: "200, 500"
    servlet:
      enabled: true

  discovery:
      etcd:
        hosts: http://localhost:2379

  config:
    etcd:
      hosts: http://localhost:2379

# Settings and configurations
skiprope-configs:
  health:
    etcd-url: http://localhost:2379/health