kumuluzee:
  name: userservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  datasources:
  - jndi-name: jdbc/userservice
    connection-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skiprope
    max-pool-size: 2

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/userservice
      disk-space-health-check:
        threshold: 100000000

  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /api/metadata/*
        status-codes: "200, 500"
    servlet:
      enabled: true

  discovery:
      consul:
        agent: http://localhost:8500

  config:
    consul:
      agent: http://localhost:8500

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                   <Configuration name="userservice">
                       <Appenders>
                           <Console name="console" target="SYSTEM_OUT">
                               <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                           </Console>
                           <Socket name="logstash" host="15398405-c4a4-4e88-b587-e80593ace71e-ls.logit.io"
                           port="13167" protocol="tcp">
                               <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                           </Socket>
                       </Appenders>
                       <Loggers>
                           <!-- Default logger -->
                           <Root level="all">
                               <AppenderRef ref="console" level="info"/>
                               <AppenderRef ref="logstash" level="trace"/>
                           </Root>
                       </Loggers>
                   </Configuration>'

# Settings and configurations
skiprope-configs:
  health:
    consul-url: http://localhost:8500/v1/status/leader