version: '3'
services:

  postgres:
    container_name: skiprope-postgres
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: skiprope
    ports:
     - 5432:5432

  consul:
    container_name: skiprope-consul
    image: "consul"
    ports:
     - 8500:8500

  userservice:
    container_name: skiprope-userservice
    build: .
    ports:
     - 8080:8080
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
     - postgres
     - consul
