kind: Service
apiVersion: v1
metadata:
  name: postgres-us
spec:
  selector:
    app: postgres-us
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-us-deployment
  labels:
    app: postgres-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-us
  template:
    metadata:
      labels:
        app: postgres-us
    spec:
      containers:
      - name: postgres-us
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: skiprope
        