kind: Service
apiVersion: v1
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: skiprope/userservice:latest
        ports:
        - containerPort: 8080
        env:
          - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
            value: http://consul:8500  
          - name: KUMULUZEE_CONFIG_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://manny.db.elephantsql.com:5432/fckauhpq
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: fckauhpq
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: hH88MKljIGnHZ3jQYbQLt-C2qGzh-Qbx
          - name: KUMULUZEE_DATASOURCES0_MAXPOOLSIZE
            value: "1"
        