apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: skiprope/userservice:latest
        ports:
        - containerPort: 8080
        env:
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul:8500  
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul:8500 
        