kind: Service
apiVersion: v1
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: skiprope/userservice:latest
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-us:5432/postgres
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: skiprope
          - name: SKIPROPECONFIGS_HEALTH_ETCDURL
            value: http://etcd:2379/health
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://userservice:8080
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: skiprope
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        